if (self.CavalryLogger) { CavalryLogger.start_js(["KBFdo"]); }

__d("MWChatForceCollapseTabs.bs",["MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","React","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,{TAG:5,_0:a})},[d,c])}f.useHook=a}),null);
__d("MWChatForceCollapseTabs.re",["MWChatForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.bs",["MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","React","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,{TAG:6,_0:a})},[d,c])}f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.re",["MWChatUndoForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatUndoForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("useToggleChatTabsOnMountUnmount",["CometRouteRenderType","MWChatForceCollapseTabs.re","MWChatUndoForceCollapseTabs.re","React","useShouldShowMessagingEntrypointOnCurrentRoute"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=b("useShouldShowMessagingEntrypointOnCurrentRoute")("CHAT"),c=b("CometRouteRenderType").useIsPushView(),d=b("MWChatForceCollapseTabs.re").useHook(),e=b("MWChatUndoForceCollapseTabs.re").useHook();g.useEffect(function(){a&&d(c);return function(){a&&e(c)}},[a,c,d,e])}}),null);
__d("CometBlurredBackgroundImage.react",["CometBackgroundImage.react","React","gkx"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h=!b("gkx")("1299319");function a(a){a=h?g.jsx("div",{className:"cg1f0npj b6s8h9p6 oqujnh0m",children:g.jsx("span",{className:"id8f4lua",children:g.jsx(b("CometBackgroundImage.react"),babelHelpers["extends"]({},a))})}):g.jsx("div",{className:"k4urcfbm datstx6m hybvsw6c"});return g.jsx("div",{className:"k4urcfbm stjgntxs ni8dbmo4 taijpn5t datstx6m j83agx80 bp9cbjyn",children:a})}}),null);
__d("CometImageCover.react",["BaseImage_DEPRECATED.react","React"],(function(a,b,c,d,e,f){"use strict";var g=b("React");d=function(){var a=document.documentElement;return a==null?!0:Boolean("objectFit"in a.style)}();function a(a){a.alt;var c=a.loading,d=a.onLoad,e=a.src,f=a.style;a=babelHelpers.objectWithoutPropertiesLoose(a,["alt","loading","onLoad","src","style"]);var h=g.useState(null),i=h[0],j=h[1],k=g.useRef();h=g.useCallback(function(){var a=k.current;if(a==null||!(a instanceof HTMLImageElement)||typeof a.src!=="string")return;j(a.src);d!=null&&d()},[d]);return i!=null?g.jsx("div",{className:"k4urcfbm bixrwtb6 datstx6m q9uorilb",style:babelHelpers["extends"]({backgroundImage:"url("+i+")",backgroundPosition:"center center",backgroundSize:"cover"},f)}):g.jsx(b("BaseImage_DEPRECATED.react"),babelHelpers["extends"]({},a,{className:"ttbfdpzt do00u71z",loading:c||void 0,onLoad:h,ref:k,src:e,style:f}))}function c(a){return g.jsx(b("BaseImage_DEPRECATED.react"),babelHelpers["extends"]({className:"k4urcfbm bixrwtb6 datstx6m q9uorilb"},a))}f=d?c:a;e.exports=f}),null);
__d("CixWarningScreensFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1743358");c=b("FalcoLoggerInternal").create("cix_warning_screens",a);e.exports=c}),null);
__d("WarningScreenType",[],(function(a,b,c,d,e,f){a=Object.freeze({GRAPHIC:"Violence and Gore",OBJECTIONABLE:"Sexual",HATE:"Hate",PROFANITY:"Profanity",POLITICAL:"Politically Charged",CHILD_ABUSE_NON_SEXUAL:"Child Abuse (non-sexual)",SENSITIVE:"Sensitive",CRUEL:"Cruel",MATURE_ONLY_14_AND_OVER:"Mature Only 14 And Over",ANIMAL_VIOLENCE:"Animal Violence",SENSITIVE_TEXT:"Sensitive Text",FALSE_NEWS:"False News",FALSE_HEADLINE_NEWS:"False Headline News",MISLEADING_NEWS:"Misleading News",ALTERED_MEDIA:"Altered Media",MISSING_CONTEXT:"Missing Context",GOVERNMENT_CORRECTION:"Government Correction",CENSUS_MISINFO:"Census Misinfo",CENSUS_BORDERLINE:"Census Borderline",COVID_ELECTION_BORDERLINE:"Covd Election Borderline",WIDELY_DEBUNKED_HOAX_COVID:"Widely Debunked Hoax Covid",HEALTH_GENERIC:"Health Generic",GENERIC_INFORM_TREATMENT:"Generic Inform Treatment",CLIMATE_GENERIC_INFORM_TREATMENT:"Climate Science Generic Inform Treatment",NEWSWORTHY:"Newsworthy",SELF_APPLIED_GRAPHIC_VIOLENCE:"Self Applied Graphic Violence",CIVIC_VOTER_INFORM_TREATMENT:"Civic Voter Inform Treatment",CIVIC_VOTER_INFORM_TREATMENT_FOR_MM:"Civic Voter Inform Treatment For Myanmar",CIVIC_VOTER_INFORM_TREATMENT_FOR_BR:"Civic Voter Inform Treatment For Brazil",CIVIC_VOTER_INFORM_TREATMENT_FOR_ID:"Civic Voter Inform Treatment For Indonesia",CIVIC_FACTS_ABOUT_VOTING_INFORM_TREATMENT:"Civic Facts About Voting Inform Treatment",HACK_AND_LEAK:"Hack And Leak",GRAPHIC_MISINFO:"Graphic Misinfo",WIDELY_DEBUNKED_HOAX_VACCINE:"Widely Debunked Hoax Vaccine",WORK_RECRUITING_GROUP_POST:"Recruiting Group Post",MISINFORMATION:"Misinformation",GENERIC_CIVIC:"Generic Civic",DUMMY_GIT:"Dummy GIT"});e.exports=a}),null);
__d("CometWarningScreenClientLogger",["CixWarningScreensFalcoEvent","WarningScreenType"],(function(a,b,c,d,e,f){"use strict";f.logWarningScreenEvent=a;function a(a,c,d,e,f,h,i,j,k,l,m,n){var o=c==null?void 0:c.split(":").filter(function(a){return a!==""}).pop();b("CixWarningScreensFalcoEvent").log(function(){return{action:a,content_id_raw:o,endpoint:d,event:e,generic_inform_treatment_case:l,integrity_ui_element:f,product:m,render_type:n,story_ent_identifier_graphql_id:h,story_render_location:i,surface:j,top_warning_screen_category:g(k)}})}function g(a){if(a==null)return null;a=a;return b("WarningScreenType")[a]}}),null);
__d("useThrottledComet",["CometThrottle","React","useLayoutEffect_SAFE_FOR_SSR"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a,c){c===void 0&&(c=100);var d=g.useRef(a);b("useLayoutEffect_SAFE_FOR_SSR")(function(){d.current=a},[a]);var e=g.useMemo(function(){return b("CometThrottle")(function(){var a=arguments;return d.current==null?void 0:d.current.apply(d,a)},c)},[c]);g.useEffect(function(){e.cancel()},[]);return e}}),null);
__d("validateTrackingCode",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="object"&&a.click_tracking_linkshim_cb!=null&&a.encrypted_click_tracking!=null&&a.encrypted_tracking!=null?a:null}}),null);
__d("validateAggregatedStoryTrackingNodeIndex",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="number"?a:0}}),null);
__d("useThrottledImpl",["cr:1708227"],(function(a,b,c,d,e,f){"use strict";e.exports=b("cr:1708227")}),null);
__d("useThrottled",["useThrottledImpl"],(function(a,b,c,d,e,f){"use strict";e.exports=b("useThrottledImpl")}),null);
__d("useUniqueID",["React","uniqueID"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=g.useRef(null);a.current===null&&(a.current=b("uniqueID")());return a.current}}),null);
__d("WarningScreenRenderType",[],(function(a,b,c,d,e,f){a=Object.freeze({FULL_COVER:"FULL_COVER",LIGHTWEIGHT:"LIGHTWEIGHT"});e.exports=a}),null);