if (self.CavalryLogger) { CavalryLogger.start_js(["q+SVg"]); }

__d("FollowInterventionDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3546987092005207",metadata:{},name:"FollowInterventionDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometGranularTimestamp.react",["fbt","CometTimestamp.react","React","formatDate","useServerTime"],(function(a,b,c,d,e,f,g){"use strict";e.exports=a;var h=b("React"),i=1e3*60*60,j=i*24;function k(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}function a(a){var c=a.date;a=a.granularity;a=a===void 0?"none":a;var d=b("useServerTime")();if(a==="none"||a==="min")return h.jsx(b("CometTimestamp.react"),{date:c});if(a==="hour"){var e=c.valueOf()%i;e=new Date(c.valueOf()-e);return h.jsx(b("CometTimestamp.react"),{date:e})}if(a==="year")return b("formatDate")(c,"Y");if(a==="month")return d.getFullYear()===c.getFullYear()?b("formatDate")(c,"F"):b("formatDate")(c,"F Y");if(k(c,d))return g._("Today");e=new Date(d.valueOf()-j);if(k(c,e))return g._("Yesterday");a=new Date(d.valueOf()+j);if(k(c,a))return g._("Tomorrow");return d.getFullYear()!==c.getFullYear()?b("formatDate")(c,"F j, Y"):b("formatDate")(c,"F j")}}),null);
__d("FollowInterventionDialog.entrypoint",["FollowInterventionDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{extraProps:a,queries:{FollowInterventionDialogQueryReference:{parameters:b("FollowInterventionDialogQuery$Parameters"),variables:{followType:a.followType,pageID:a.pageID,scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("FollowInterventionDialog.react").__setRef("FollowInterventionDialog.entrypoint")};e.exports=a}),null);
__d("VideoHomeCometErrorBoundary.react",["CometErrorBoundary.react","React","VideoHomeTypedLoggerLite"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){var c=g.useCallback(function(c){b("VideoHomeTypedLoggerLite").log({event:"js_error",exception:c.message,exception_trace:c.componentStack,module_class:a.moduleClass,unit_position:a.unitPosition})},[a.moduleClass,a.unitPosition]);return g.jsx(b("CometErrorBoundary.react"),{context:{project:"www_watch"},fallback:a.fallback,onError:c,children:a.children})}}),null);
__d("CometVideoHomeThreeDotContextMenuWrapperContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({contextMenuEnabled:null});e.exports=c}),null);
__d("CometVideoHomeFunnelLoggingContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({hasPermalinkInjection:!1});e.exports=c}),null);
__d("CometVideoHomeSectionPositionContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("CometVideoHomeShowSurfacesLoggingContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({entrypoint:"",pageID:null,sectionTypeName:"",surface:""});e.exports=c}),null);
__d("VideoHomeGlobalSoundContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({muted:!0,setMuted:function(){},setVolume:function(){},volume:1});e.exports=c}),null);
__d("VideoHomeLoggingUpstreamPlayerSourceContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("WebFunnelLogger",["invariant","Banzai"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){this.$2={},this.$3={},this.$4="web_funnel_logging",this.$5(),this.$1.funnel_definition=a}var c=a.prototype;c.log=function(){this.$1.funnel_payload=JSON.stringify(this.$2),this.$1.action_payload=JSON.stringify(this.$3),b("Banzai").post(this.$4,this.$1,b("Banzai").BASIC),this.$5()};c.logWithEventTime=function(a){this.$1.event_time=a/1e3,this.$6(),b("Banzai").post(this.$4,this.$1,b("Banzai").BASIC),this.$5()};c.logVital=function(){this.$6(),b("Banzai").post(this.$4,this.$1,b("Banzai").VITAL),this.$5()};c.logVitalWithEventTime=function(a){this.$1.event_time=a/1e3,this.$6(),b("Banzai").post(this.$4,this.$1,b("Banzai").VITAL),this.$5()};c.$6=function(){this.$1.funnel_payload=JSON.stringify(this.$2),this.$1.action_payload=JSON.stringify(this.$3),this.$1.action!==null||g(0,5829),this.$1.session_key!==null||g(0,5830)};c.$5=function(){this.$1={};this.$2={};this.$3={};return this};c.setAction=function(a){this.$1.action=a;return this};c.addActionPayload=function(a,b){this.$3[a]=b;return this};c.setActionTag=function(a){this.$1.action_tag=a;return this};c.addFunnelPayload=function(a,b){this.$2[a]=b;return this};c.setFunnelTags=function(a){this.$1.funnel_tags=a;return this};c.setSecondaryOrder=function(a){this.$1.secondary_order_value=a;return this};c.setSessionKey=function(a){this.$1.session_key=a;return this};c.markStart=function(){this.$1.session_marker="start";return this};c.markEnd=function(){this.$1.session_marker="end";return this};c.setUserId=function(a){this.$1.user_id=a;return this};c.setIsEmployee=function(a){this.$1.is_employee=a;return this};return a}();e.exports=a}),null);
__d("logVideoHomeWebFunnel",["CurrentUser","WebFunnelLogger","gkx"],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a,c,d,e){if(!b("gkx")("1238150"))return;var f=new(b("WebFunnelLogger"))("VideoHomeWWWFunnelDefinition").setAction(a).setSessionKey(b("CurrentUser").getID());c!=null&&Object.entries(c).forEach(function(a){var b=a[0];a=a[1];f.addFunnelPayload(b,a)});d!=null&&Object.entries(d).forEach(function(a){var b=a[0];a=a[1];f.addActionPayload(b,a)});e&&f.markStart();f.log()}}),null);
__d("CometVideoHomeInjectionPortalingContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({initialTracePolicy:null,injectedVideoID:null,portableVideoID:null,subOrigin:null});e.exports=c}),null);
__d("XCometVideoHomeLiveControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f){a=b("jsRouteBuilder")("/watch/live/",Object.freeze({}),void 0);c=a;e.exports=c}),null);